### ISSUE TITLE
Is it possible to get available dates from a TimeDimension?

### ISSUE THREAD

**Issue by romran-altic** [khaeru/sdmx#173]
Hello, I am trying to get dimensions explanations with:
`cl = structure.dimensions.get(dimension).local_representation.enumerated`
`sdmx.to_pandas(cl)`
Is there any possible approach to get available dates from `TimeDimension` because code above returns empty.
Asking because I need to get min max date or available dates list from smdx metadata.
Thanks for your help :)

**Comment by khaeru** [comment]
Hi there!

This is a general SDMX question, and doesn't have much to do with this package. It's also hard to answer because you don't say which particular data provider and structures you are working with. For instance, where do you get `structure` and `dimension` from? This is necessary info because each data provider chooses different ways to use the SDMX standard to represent their data.

**In general**—again, these are all features of the SDMX standard or ways it is commonly used, nothing about this package:
- The [Representation](https://sdmx1.readthedocs.io/en/latest/api/model.html#sdmx.model.common.Representation) (of a dimension in a data structure) can be *either* enumerated *or* non-enumerated.
  - "Enumerated" means "only values appearing in a specific code list"—it seems like you're aware fo this.
  - "Non-enumerated" data has no associated code list. It can still have specific formats. These are specified using [Facet](https://sdmx1.readthedocs.io/en/latest/api/model.html#sdmx.model.common.Facet) and related classes. For example, a non-enumerated representation can be specified as "a string with format YYYY-MM", or something like that.
- Many data providers use enumerated representations for most dimensions, yet *not* for `TIME_PERIOD` or similar. This would imply there is no codelist that gives allowable values of that dimension.
- I think it is possible to use SDMX's constraints mechanisms to specify allowable (a list, or min/max) values of a non-enumerated dimension. But I say "I think" because this is not very common; I don't think most of the known data providers do this.

But again:
- The purpose of this package and its documentation [is not to repeat the SDMX standards documents](https://sdmx1.readthedocs.io/en/latest/index.html#not-the-standard). I encourage you to read them, or some of the [learning resources](https://sdmx.org/?page_id=2555) on the official SDMX website.
- Without saying specifically which (meta)data you are working with, it's not possible to say whether this package is working correctly, or if there is specific information you can retrieve. If you can provide a [“minimal working example”](https://en.wikipedia.org/wiki/Minimal_reproducible_example) then we can discuss this.

**Comment by romran-altic** [comment]
Hello, many thanks for your detailed answer. Currently I am trying to get `PRC_HICP_CMON` table from `ESTAT` source. 
`table_msg = self.sdmx_client.dataflow(table)`
`table_flow = table_msg.dataflow[table]`
`structure = table_flow.structure`

As mentioned for `TIME_PERIOD` component with `structure.dimensions.get('TIME_PERIOD').local_representation` I could get Facet:

`<Representation: None, [Facet(type=FacetType(is_sequence=None, min_length=None, max_length=None, min_value=None, max_value=None, start_value=None, end_value=None, interval=None, time_interval=None, decimals=None, pattern=None, start_time=None, end_time=None, sentinel_values=None), value=None, value_type=<FacetValueType.observationalTimePeriod: 18>)]>`

I noticed `value_type=<FacetValueType.observationalTimePeriod: 18>)]>`  my understanding that it contains 18 values. Could you know if it's possible to retrieve any data from this class?
