### ISSUE TITLE
SDMX-ML element order issue

### ISSUE THREAD

**Issue by 3nz01** [khaeru/sdmx#210]
My team and I are using sdmx1 to create a dataflow which we are subsequently uploading to .Stat. sdmx1 created the dataflow without any problem, but when we tried to upload this file, we experienced a vague error from .Stat about the Annotation element. See more details [here](https://gitlab.com/sis-cc/.stat-suite/dotstatsuite-data-lifecycle-manager/-/issues/483).

 We reached out to the .Stat team and found that in SDMX-ML, the order of elements is fixed. The error was caused due to the fact that the Annotation element was in the wrong order and that the file created by sdmx1 dataflow did not adhere to this take rule.

 Perhaps we are using sdmx1 incorrectly, but we were not able to find any way to ensure this order constraint was being taken into account. We have a workaround in place, but we wanted to flag this with you in case it was in fact a bug.

**Comment by khaeru** [comment]
Thanks for this report! Great to see fellow Canadians using the package.

Prior to reading the full discussion at the issue you linked, I would guess that this is indeed a bug. Some explanation:
- There are official XSD Schema files published for SDMX-ML. The ones for SDMX-ML 2.1 are [here](https://github.com/sdmx-twg/sdmx-ml/tree/v2.1). In this particular case we can look at [SDMXStructureDataflow.xsd](https://github.com/sdmx-twg/sdmx-ml/blob/bc28a2255966a3b8d33ec8f61e19f42e6e193284/schemas/SDMXStructureDataflow.xsd#L18-L21):
  ```xml
  <xs:sequence>
    <xs:element ref="common:Annotations" minOccurs="0"/>
    <xs:element ref="common:Name" maxOccurs="unbounded"/>
    <xs:element ref="common:Description" minOccurs="0" maxOccurs="unbounded"/>
  ```
  …here the `<xs:sequence>` in XSD has the specific meaning "the following elements may/must appear **in this exact sequence**."
- The present package, `sdmx1`, has a large number of tests for reading and writing SDMX-ML. In particular, these include “round-trip” tests: content is read from SDMX-ML and then written, or written and then read (sometimes even a 3-step sequence of R-W-R, or W-R-W).
  - However, in all cases, the 'read' step is tested **using `sdmx1` itself**, particularly the `sdmx.reader.xml` code. This code is deliberately crafted to be tolerant of a lot of SDMX-ML seen “in the wild” that is technically non-compliant yet actually returned by one or another of the supported data providers. In particular, the code is mostly forgiving of elements being out of sequence. If, for instance, `<common:Description …>` appears before `<common:Name …>`, the code will parse it without complaint.
  - Thus I suspect this is a case where `sdmx1` generates invalid SDMX-ML, but of a kind that it itself tolerates in read operations, so that these tests pass happily. On the other hand, the .Stat implementation is designed to be strict, and expects the elements to be in order. (There are other possible implementation choices. One example, seen in contexts other than SDMX, is to have a configuration option like "quirks mode" that, when set, causes code to accept technically non-standard input, but when unset raises exceptions.)
- @goatsweater in #154 added features to fetch and apply the XSD schemas. In reviewing that PR, I made [this comment](https://github.com/khaeru/sdmx/pull/154#pullrequestreview-1826871349); to quote the key part:
  > `test_validate_xml_invalid_doc()` raises the important question of whether `sdmx.to_xml()` should *ever* generate invalid SDMX-ML—or put another way, whether it should *guarantee* valid SDMX-ML. I think this would be a nice enhancement to .writer.xml, but would require detailed tests to support.

  This is still the case: it *would be* a nice enhancement, but no one has worked on it.

As for what we can do:
- If you can, please try to use those features to fetch and apply the schemas to the dataflow definition you have generated, and report here what kind of results you get. Such code could then be turned into a test.
- I suspect the responsible code is this:
  https://github.com/khaeru/sdmx/blob/4116706e39be31064e7e109fe17603d34455d9bb/sdmx/writer/xml.py#L300-L303
  - If code calling `annotable()` passes `args` as a list of other sub-elements for the tag to be created, *and* there are annotations, then the annotations are *appended* to the `args`. To comply with the schemas they should be *prepended*.
  - I suspect this would be a simple fix. Again, please let me know if you are able to test this and then report your experience and/or open a PR. If not I will get to it as soon as time allows.

**Comment by 3nz01** [comment]
Hey Paul,
 thanks so much for your prompt response, excellent analyses and easy
to read explanation. :) Yes... many Canadians are using the package here at
StatCan. It is a pretty common part of our workflow and you'll be happy to
know that any SDMX data you get from us has probably been touched by it.
We'll take a look at testing your fix and get back to you. Thanks again.

Best regards,
 Mark
