### ISSUE TITLE
HTTP[S]_PROXY environment variables appear to be ignored

### ISSUE THREAD

**Issue by bertrandmarc** [khaeru/sdmx#26]
It appears that HTTP_PROXY and HTTPS_PROXY variables are ignored by sdmx1, although they are taken into account by standard requests. If this is relevant, my proxy uses basic authication (HTTP_PROXY='http://user:pwd@proxyurl:port')

Please see the examples below:
```python
import sdmx
insee = sdmx.Request('INSEE')
insee.dataflow()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\sdmx\api.py", line 416, in get
    raise e from None
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\sdmx\api.py", line 413, in get
    response = self.session.send(req)
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bdm.insee.fr', port=443): Max retries exceeded with url: /series/sdmx/dataflow/ALL/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A886E2DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

# However it works with manual configuration from the environment variables
from os import environ
insee = sdmx.Request('INSEE', proxies = {'http': environ['HTTP_PROXY'], 'https': environ['HTTPS_PROXY']})
insee.dataflow()
<sdmx.StructureMessage>
  <Header>
    id: 'dataflows_*_1605862772527'
    prepared: '2020-11-20T09:59:32.527000+01:00'
    receiver: <Agency unknown>
    sender: <Agency FR1: Institut national de la statistique et des études économiques>
    source: fr: Banque de données macro-économiques
    test: False
  response: <Response [200]>
  DataflowDefinition (212): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONAL CLI...
  DataStructureDefinition (199): BALANCE-PAIEMENTS CHOMAGE-TRIM-NATIONA...

# It works without manual configuration with requests
import requests
requests.get('https://www.bdm.insee.fr/series/sdmx/dataflow/ALL/latest')
<Response [200]>
```

**Comment by khaeru** [comment]
Good catch, and thanks for including the workaround.

At a quick glance, the **issue** seems to be that we create a `requests.Session()` object: https://github.com/khaeru/sdmx/blob/01db026af35d98715ccd9c3509b7d1ab44297b5e/sdmx/api.py#L60

and then separately create a `requests.Request` object and call `session.prepare_request()` on it:
https://github.com/khaeru/sdmx/blob/01db026af35d98715ccd9c3509b7d1ab44297b5e/sdmx/api.py#L243
https://github.com/khaeru/sdmx/blob/01db026af35d98715ccd9c3509b7d1ab44297b5e/sdmx/api.py#L395

The code in `requests` that does similar things next specifically *copies the proxy configuration* from the `Session` object and prepares keyword arguments to `Session.send()`: https://github.com/psf/requests/blob/02eb5a2/requests/sessions.py#L515-L544 —sdmx1 doesn't do this, so this is probably why they fail to pass through.

The **fix** will be to imitate what `requests` does. In that sense, this is related to #11.
**Testing** will be a little more difficult, since I haven't before set up tests using HTTP proxies, but we can follow the example of [tests from `requests` itself](https://github.com/psf/requests/blob/320a10d142a7cbe224f0dcb1732484fff08cdd8e/tests/test_requests.py).
