### ISSUE TITLE
Validate SDMX-ML output using XSD

### ISSUE THREAD

**Issue by khaeru** [khaeru/sdmx#51]
(Copied from the former [doc/roadmap.rst](https://github.com/khaeru/sdmx/blob/896eee2/doc/roadmap.rst).)

The schemas are available on GitHub:
https://github.com/sdmx-twg/sdmx-ml-v2_1/tree/master/schemas

This could be skipped by default, but provided as a public function (in e.g. `sdmx.format.xml`) and used in the test suite.

This would help guard against issues like #42.

**Comment by brockfanning** [comment]
@khaeru I'm interested in some other validation-related features. I'm not sure if these would be covered by this XSD-based validation. In particular, here are the features I'm thinking of:

1. Validate that an SDMX data message does not reference any codes that are not in an associated DSD
2. Validate that an SDMX data message does not contain any duplicate observations (ie, 2+ observations with the same series key)

Do you think that this XSD-based validation would overlap with those features? If not, I can start separate issues, if you think that either/both would be in scope for this library.

**Comment by khaeru** [comment]
@brockfanning both would be useful enhancements, yes! Please open separate issues.

For (2), it's indeed invalid for there to be duplicate keys in the same data _set_. However, to be precise:
- A data _message_ can contain multiple data sets, and it's entirely valid for the same key to occur twice or more in the message—so long as each occurrence is in a different data _set_.
- _Series keys_ exist to avoid duplicating key values for multiple observations, so it's intended that 2 or many observations can be associated with 1 _series_ key. (These can be collectively thought of as "a series", although there is no specific class for this in the IM.) The thing that cannot be duplicated within a data set is the _entire_ key, i.e. the key values on the series key _together with_ key value(s) on the observation itself.
  - In "flat" data, there are no series keys, and key values for _all_ dimensions are attached to each observation.
  - In typical series-structured data, key values for all but one dimension are specified via the series key, and then only one dimension has key values attached to the observation.

**Comment by goatsweater** [comment]
I'm interested in taking a stab at implementing XSD validation, but I'm curious about the vision for implementation. In my mind there isn't a lot of value in a public `validate()` method on objects because:

1. The XSDs don't really support validating *every* object and it isn't clear to me how to add the method only on supported objects given how `sdmx.format.xml` works.
2. Users should be able to trust that outputs are valid for what the standard defines. The fact that you can dump partial objects/XML output is valuable, but then a user shouldn't expect it to validate without additional effort.
3. I don't think the intention is to ship the XSDs with the library, and thus calls to `validate()` would fail in an offline environment. This would be unexpected and likely lead to increased issues.

With the above in mind, I think it makes sense to run validations in the test suite. For everything defined within the XSDs a set of tests that provide as comprehensive a coverage as possible would be generated, thus catching all the sub-objects. When users then dump a `Code` to XML it would be valid by nature of validating a structure message containing a codelist.

**Comment by khaeru** [comment]
@goatsweater great to hear you're interested to contribute. Some thoughts, in no particular order:

- XSD validation is of XML documents. So I agree there should not be anything like `validate(Code())` or `Code.validate()`. Rather, there should be some top-level method like `sdmx.validate_xml(…)` function that, like `sdmx.read_sdmx(…)`, takes a path to a file, or a buffer (text/bytes).
- As you say, if only a snippet has been converted to XML, XSD validation becomes complicated. I think it's fine if the code notices and politely refuses to proceed (for instance, `raise NotImplementedError`) unless the top-level element in the input is `<mes:DataMessage>`, `<mes:StructureMessage>` or similar. Someone else could later expand the implementation.
- Since we already depend on `requests`, I would probably create a simple utility function that fetches the schemas from their known location on GitHub (I don't think there is any more "official" or permanent/archival location) and unpacks them to a local directory (`xdg_base_dirs.xdg_cache_home` or similar). Then:
  - This code can be called in the GHA workflows, or even run automatically by the Pytest session start hook (for local development).
  - We can supply users with instruction on how to do this on their own end, as part of documentation for the new top-level function. If they try to call the method _before_ doing this, they should see an exception with text that clearly points to the docs.

    I think you are right that, in practice, few users will actually want to do this. But my usual approach is just to expose all this "internal" utility code, document it for ease of maintenance, and let people use it if they like.
- As far as I know the maintainer of pandaSDMX tried to add this as a feature, so you might look there for inspiration, but please don't be bound by it (especially if the implementation is messy).
- I have not given much thought to how this should work given there are now at least 2 (SDMX-ML 2.1 and 3.0.0) sets of XSDs.

**Comment by goatsweater** [comment]
My brain never went to a top level method, but that completely makes sense now that you've pointed it out. I'll take a look at the pandasdmx as inspiration and see what I can come up with.
