### ISSUE TITLE
How to distinguish series attributes and observation attributes?

### ISSUE THREAD

**Issue by brockfanning** [khaeru/sdmx#57]
I'm likely using the wrong terms here, but I need to loop through the attributes in a DSD and identify which ones are attributes of a series, and which are attributes of an observation. Here is some code that I'm using to do this:

```
dsd = get_my_dsd()
for attribute in dsd.attributes:
  if attribute.related_to is not None and isinstance(attribute.related_to, sdmx.model._PrimaryMeasureRelationship):
    print('This is an observation attribute.')
  if attribute.related_to is not None and isinstance(attribute.related_to, sdmx.model.DimensionRelationship):
    print('This is a series attribute.')
```

I'm sure there is a better way, especially since that is using internals of the API. Any advice on a more proper way to do this would be greatly appreciated!

**Comment by khaeru** [comment]
That's basically it!

The statement "DataAttribute <A> is attached to a series" is equivalent to "`A.related_to` is an instance of `DimensionRelationship`." That's how the standard/IM specifies that relationship. The package doesn't add any shorthand for this outside of what is in the standards.

I see from the leading underscore on `_PrimaryMeasureRelationship` that you are using [2.0.1](https://sdmx1.readthedocs.io/en/latest/whatsnew.html#v2-0-1-2021-01-31). So one easier way to do that comparison is:
```python
…and attribute.related_to is sdmx.model.PrimaryMeasureRelationship
```
The `is` operator works because (like Python `None`) there is only one object instance of this class. The same is not true of `DimensionRelationship`, because each instance of that class has different properties.

If you want to make the code a little shorter, you can do things like this:
```python
# Do this to make access to model classes shorter
import sdmx.model as m

dsd = get_my_dsd()
attr_info = dict()

for a in dsd.attributes:
    if a.related_to is None:
        value = "none"
    elif a.related_to is m.PrimaryMeasureRelationship:
        value = "observation"
    elif isinstance(a.related_to, m.DimensionRelationship):
        value = "series"
    attr_info[a.id] = value
```

or even this, although I'd only recommend this if you find yourself typing the class names dozens of times:
```python
from sdmx.model import (
    # Rename on import
    PrimaryMeasureRelationship as PMR,
    DimensionRelationship as DR
)
…
```

Keep in mind that GroupRelationship and NoSpecifiedRelationship also exist. I also wonder if `NoSpecifiedRelationship` should be the default, instead of `None` 🤔 …will check.

**Comment by khaeru** [comment]
>  I also wonder if `NoSpecifiedRelationship` should be the default, instead of `None` thinking …will check.

Do you have particular example (meta)data in which attributes have `related_to is None`?

**Comment by brockfanning** [comment]
Thanks! I am much happier to use `is PrimaryMeasureRelationship` -- the underscore was my main concern. :)

Also appreciate the reference to the IM - I will check that out.

I just added some debug statements, and it turns out that the `None` never actually comes up - so I must have added that unnecessarily.

Thanks again! My question is definitely answered so I'll close this.
