### ISSUE TITLE
Updating ILO url

### ISSUE THREAD

**Issue by ethangalebach** [khaeru/sdmx#96]
I am running into an issue using `sdmx.Client("ILO").get()`. 

I believe the ILO url in [sources.json](https://github.com/khaeru/sdmx/blob/main/sdmx/sources.json#L66) is outdated and should be updated to `http://www.ilo.org/sdmx/rest`. This is indicated by the [ILO query builder](https://ilostat.ilo.org/resources/sdmx-tools/#query-builder), which outputs urls like: `https://www.ilo.org/sdmx/rest/data/ILO,DF_ILR_TUMT_NOC_RT/?format=jsondata&startPeriod=2012-01-01&endPeriod=2022-12-31&firstNObservations=500`

With this change, I still get a 422 error message due to a missing `/ILO,` component of the url. This might be fixed by updating the lines around [here](https://github.com/khaeru/sdmx/blob/main/sdmx/client.py#L221) in client.py so that the `provider` keyword is compatible with `resource_type='data'`.

I'd be happy to make a PR if that is preferable.

Thanks for your time!

**Comment by khaeru** [comment]
Thanks for the precise report! A PR updating the URL would be very welcome.

Per the 422, here's the description of the SDMX 2.1 REST web service URL syntax: https://github.com/sdmx-twg/sdmx-rest/blob/v1.5.0/v2_1/ws/rest/docs/4_4_data_queries.md:
> `protocol://ws-entry-point/resource/flowRef/key/providerRef`

You can see that it technically *is* possible to include the provider ID (providerRef) in the URL. But if this is done, it must come *after* the key. So if the URL you give were actually specifying the providerRef part, it would look something like:
> `https://www.ilo.org/sdmx/rest/data/DF_ILR_TUMT_NOC_RT/<key>/ILO`

I suspect what is actually going on here is that this data source is using data flow IDs containing a comma, i.e. `ILO,DF_ILR_TUMT_NOC_RT` is the valid data flow ID, rather than simply `DF_ILR_TUMT_NOC_RT`. Are you able to retrieve data if you specify the former ID?

**Comment by ethangalebach** [comment]
Thank you for the helpful link about sdmx syntax. I was mistaken to think the the provider ID was the cause. I will add the appropriate prefix to the `resource_id` keyword in the future. 

The last issue I face is with the `references` parameter defaulting to 'none'. For instance, when I 
> curl  'https://www.ilo.org/sdmx/rest/data/ILO,DF_ILR_TUMT_NOC_RT?startperiod=2019-01-01&endperiod=2019-12-31&firstNObservations=500&format=jsondata&references=none'

I receive this error message: 

> Unknown query parameter  'references' allowed parameters [startPeriod, endPeriod, updatedAfter, firstNObservations, lastNObservations, dimensionAtObservation, detail]

Is there is any concern with removing [the setting of an ILO default value](https://github.com/khaeru/sdmx/blob/main/sdmx/source/ilo.py#L24) for the `references` parameter? It seems this parameter is only valid when `resource_type='dataflow'` and not when `resource_type='data'` based on the ILO query builder.
